name: dels_smartbill
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_riverpod: ^3.0.3
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  uuid: ^4.5.1
  workmanager: ^0.9.0+3
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  floor: ^1.5.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  logger: ^2.0.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - .env